name: Release

on:
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  binaries:
    name: Build release binaries.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Install yarn.
        run: npm install -g yarn
      - name: Install dependencies.
        run: yarn install
      - name: Build.
        run: yarn build:binaries

      - uses: actions/upload-artifact@v3
        with:
          name: kyve-bitcoin-linux
          path: ./out/bitcoin-linux
      - uses: actions/upload-artifact@v3
        with:
          name: kyve-bitcoin-macos
          path: ./out/bitcoin-macos
      - uses: actions/upload-artifact@v3
        with:
          name: kyve-bitcoin-win.exe
          path: ./out/bitcoin-win.exe

  docker:
    name: Build and publish Docker container.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker.
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image.
        run: docker build -t kyve/bitcoin:${GITHUB_REF#refs/tags/} -t kyve/bitcoin:latest .

      - name: Push to Docker hub.
        run: docker push -a kyve/bitcoin

  webhook:
    name: Post a message to Discord.
    needs: [binaries, docker]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Install yarn.
        run: npm install -g yarn
      - name: Install dependencies.
        run: yarn install

      - name: Run script.
        run: DISCORD=${{ secrets.DISCORD }} VERSION=${GITHUB_REF#refs/tags/} node .github/webhook.js
